# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Tests"

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Use Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g npm@latest
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Validate Format
        run: npm run format
      - name: Validate Style
        run: npm run lint
