# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Tests"

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    name: Use Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm install
      - name: Validate Format
        run: pnpm run format
      - name: Validate Style
        run: pnpm run lint
      - name: Run the tests
        run: pnpm run test
