name: Validate Code

on:
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Check format
        run: pnpm format

      - name: Check lint
        run: pnpm lint

      - name: Check types
        run: pnpm type

      - name: Check tests
        run: pnpm test

      - name: Check build
        run: pnpm build
