name: Validate Code

on:
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Run formatter
        run: pnpm format

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Run linter
        run: pnpm lint

  types:
    runs-on: ubuntu-latest
    name: Types
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Run type
        run: pnpm type

  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Run build
        run: pnpm build
